#!/usr/bin/env bash
#PBS -q gpuq
#PBS -l ncpus=64
#PBS -l mem=64Gb
#PBS -l walltime=00:05:00

#$ -cwd
#$ -S /bin/bash
#$ -pe orte-32-ib.pe 32

source /etc/profile.d/modules.sh

echo "Load singularity..."
module load singularity/3.4.1
echo "Executing singularity..."
singularity exec --nv --bind $DATAWORK/:/datawork $HOME/Singularities/tf2.6.0_retinanet.sif python $HOME/CODE/IFREMER-ABYSSES/Datarmor_Tests/First_Prove.py
