#!/usr/bin/env bash
#PBS -q gpuq
#PBS -l select=1:ncpus=4:ngpus=1:mem=11g
#PBS -l walltime=72:00:00

#$ -cwd
#$ -S /bin/bash


source /etc/profile.d/modules.sh

echo "Load singularity..."
module load singularity/3.4.1
echo "Executing singularity..."
singularity exec --nv --bind $DATAWORK/:/datawork $HOME/Singularities/tf1.15.5-gpu_rs.sif python $HOME/CODE/IFREMER-ABYSSES/Transfer_Learning/TF115/Main_Script_For_Running_Lithology_AllSets.py --running_in Datarmor_PBS --phase train
