#!/usr/bin/env bash
#PBS -q gpuq
#PBS -l select=1:ncpus=4:ngpus=1:mem=32g
#PBS -l walltime=48:00:00

#$ -cwd
#$ -S /bin/bash


source /etc/profile.d/modules.sh

echo "Load singularity..."
module load singularity/3.4.1
echo "Executing singularity..."
singularity exec --nv --bind $DATAWORK/:/datawork $HOME/Singularities/tf2.6.0_retinanet.sif python $HOME/CODE/IFREMER-ABYSSES/Object_Detector/RetinaNet/running_script.py --running_in Datarmor_PBS --phase Train
