#!/usr/bin/env bash
#PBS -q gpuq
#PBS -l select=1:ncpus=4:ngpus=1:mem=32g
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -m n
#PBS -r n
#PBS -S /bin/bash

DATAWORK = /datawork/fsi1/home1/pjsotove

cd ${PBS_O_WORKDIR}

echo "Load singularity..."
module load singularity/3.4.1
echo "Executing singularity..."
singularity exec --nv --bind ${DATAWORK}:/datawork ${HOME}/Singularities/tf1.15.5-gpu_rs.sif python ${HOME}/CODE/IFREMER-ABYSSES/Transfer_Learning/TF115/Main_Script_For_Running_Morphology_Comitee_MS.py
#singularity exec --nv --bind ${DATAWORK}:/datawork ${HOME}/Singularities/tf1.15.5-gpu_rs.sif python ${HOME}/CODE/IFREMER-ABYSSES/Transfer_Learning/TF115/Main_Script_For_Running_Morphology_Comitee_WC.py
#singularity exec --nv --bind ${DATAWORK}:/datawork ${HOME}/Singularities/tf1.15.5-gpu_rs.sif python ${HOME}/CODE/IFREMER-ABYSSES/Transfer_Learning/TF115/Main_Script_For_Running_Morphology_Comitee_ET.py
